language: python
sudo: true
cache: pip

python:
  - "2.7"

dist: trusty

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-cairo
      - cups
      - libcups2-dev

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - if [[ ${TESTS} == "1" ]]; then sudo apt-get -qy install libreoffice; fi
  - if [[ ${TESTS} == "1" ]]; then sudo apt-get -qy install python-genshi; fi
  - if [[ ${TESTS} == "1" ]]; then sudo apt-get -qy install python-cairo; fi
  - if [[ ${TESTS} == "1" ]]; then sudo apt-get -qy install python-cups; fi
  - git clone --depth=1 https://github.com/open-synergy/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone https://github.com/aeroo/aeroolib.git ${HOME}/aeroolib
  - pushd ${HOME}/aeroolib; git checkout b591d23c98990fc358b02b3b78d46290eadb7277; sudo python ./setup.py install; popd

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
